---
main_pkg:
  - mc
  - wget
  - vim
  - gcc
  - unzip
  - htop
  - tmux
  - curl
  - pkg-config
  - python-pip
  - python-dev
  - libpq-dev
  - build-essential
  - python-pycurl

setup_zsh: True
git_user_name: "{{application_name}}"
git_email: git@{{application_name}}
