---
add_pkgs:
  - build-essential
  - gettext
  - python-dev
  - zlib1g-dev
  - libpq-dev
  - libtiff4-dev
  - libjpeg8-dev
  - libfreetype6-dev
  - liblcms1-dev
  - libwebp-dev
  - graphviz-dev
  - python-setuptools
  - python3-dev
  - python-virtualenv
  - python-pip
  - automake
  - libtool
  - libreadline6
  - libreadline6-dev
  - libreadline-dev
  - libsqlite3-dev
  - libxml2
  - libxml2-dev
  - libssl-dev
  - libbz2-dev
  - wget
  - curl
  - llvm

virtualenv_path: "{{application_path}}/.env"
git_branch: master

# Gunicorn
gunicorn_num_workers: 2
gunicorn_max_requests: 0

# Django Environment variables
requirements_file: "{{application_path}}/requirements.txt"
django_environment:
  DEBUG: False
  DATABASE_URL: sqlite:////tmp/my-tmp-sqlite.db
  DJANGO_SECRET_KEY: be&9u)d64q^@a__^1oswsezz((%li@j^5#=f!lm32n+21x!*2@
  DJANGO_ALLOWED_HOSTS: "*"

django_settings_file: "{{application_path}}/config/settings/production"
django_wsgi: "config.wsgi"

django_manage_commands:
  - migrate
  - collectstatic
